server:
  port: 2002


spring:
  application:
    name: USER-SERVICE
  datasource:
    username: DB_USER
    password: DB_PASSWORD
    url: jdbc:mysql://localhost:3306/dblatihan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  zipkin:
    base-url: http://127.0.0.1:9411/

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
